SELECT DISTINCT
    PARENT.ITEM_ID,
    PARENT.ITEM_NAME,
    PARENT.RARITY
FROM
    (
        SELECT
            ITEM_INFO.ITEM_ID,
            ITEM_INFO.ITEM_NAME,
            ITEM_INFO.RARITY,
            ITEM_TREE.PARENT_ITEM_ID
        FROM
            ITEM_INFO JOIN ITEM_TREE
            ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
    ) AS PARENT
    LEFT JOIN
    (
        SELECT
            ITEM_INFO.ITEM_ID,
            ITEM_INFO.ITEM_NAME,
            ITEM_INFO.RARITY,
            ITEM_TREE.PARENT_ITEM_ID
        FROM
            ITEM_INFO JOIN ITEM_TREE
            ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
    ) AS CHILD
    ON CHILD.PARENT_ITEM_ID = PARENT.ITEM_ID
WHERE
    CHILD.ITEM_ID IS NULL
ORDER BY
    PARENT.ITEM_ID DESC;