SELECT DISTINCT
    CAR.CAR_ID,
    CAR.CAR_TYPE,
    TRUNCATE(CAR.DAILY_FEE * ((100 - PLAN.DISCOUNT_RATE) / 100) * 30, 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS CAR
    JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상'
    ) AS PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE
    CAR.CAR_TYPE IN ('세단', 'SUV')
    AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
    )
HAVING
    FEE >= 500000 AND FEE < 2000000
ORDER BY
    FEE DESC,
    CAR.CAR_TYPE ASC,
    CAR.CAR_ID DESC;
