SELECT
    MEMBER.MEMBER_NAME,
    REVIEW.REVIEW_TEXT,
    DATE_FORMAT(REVIEW.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    MEMBER_PROFILE AS MEMBER
    JOIN
        REST_REVIEW AS REVIEW
        ON MEMBER.MEMBER_ID = REVIEW.MEMBER_ID
WHERE
    (
        SELECT COUNT(*)
        FROM REST_REVIEW AS R2
        WHERE R2.MEMBER_ID = MEMBER.MEMBER_ID
    ) = (
        SELECT MAX(COUNTS.REVIEW_COUNT)
        FROM (
            SELECT COUNT(*) AS REVIEW_COUNT
            FROM REST_REVIEW AS R3
            GROUP BY R3.MEMBER_ID
        ) AS COUNTS
    )
ORDER BY
    REVIEW.REVIEW_DATE ASC,
    REVIEW.REVIEW_TEXT ASC;