SELECT DISTINCT DEV.ID, DEV.EMAIL, DEV.FIRST_NAME, DEV.LAST_NAME
FROM DEVELOPERS AS DEV LEFT JOIN SKILLCODES AS SC
ON DEV.SKILL_CODE & SC.CODE = SC.CODE
WHERE SC.NAME = "Python" OR SC.NAME = "C#"
ORDER BY ID ASC;